### PR TITLE
Next gen, sgds

### PR DESCRIPTION
**Pull request by weijunyu**
Updated to make use of latest sgds css/js builds.
- sgds.css and sgds.js imported from cdn in `<head>` and `<body>`
- blueprint.css now separated into main.css and sgds-custom.css
- main.css contains general styles
- sgds-custom.css contains rules that override or extend sgds classes
- added some fixes in theme-colors/custom.scss
- removed common.js which targeted an old build of sgds, whose logic is now handled by sgds.js.
- main.js controls behaviour for non-sgds elements (mobile nav + accordion)
- various minor fixes

### CODE REVIEW

**Comment by LoneRifle** [comment]
@weijunyu - I'm probably gonna look at this later. Do we have access to your branch (this can be granted via the PR)?

**Comment by weijunyu** [comment]
Thanks Alvin :)
I've granted your account access to the downstream repo since the option to grant through the PR is missing for some reason
Will look through the PR again since the codebase would have progressed a lot since then

**Comment by LoneRifle** [comment]
I'm going to do a rebase and merge as the result will be cleaner to reason about. Hope that's ok.

**Comment by LoneRifle** [comment]
Example site generated, message me for details

**Pull request closed without merging**
